modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="codpattern_zombies"
version="${mod_version}"
displayName="COD Pattern Zombies"
authors="${mod_authors}"
description='''COD Pattern Zombies addon'''

[[dependencies.codpattern_zombies]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.codpattern_zombies]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.codpattern_zombies]]
modId="codpattern"
mandatory=true
versionRange="${codpattern_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.codpattern_zombies]]
modId="tacz"
mandatory=true
versionRange="[1.1.6,)"
ordering="AFTER"
side="BOTH"
